import {TStackResourcesParam} from '@/types/application/Navigation/NavigationApplication.types'

export const nameScreenAnalytics: Record<keyof TStackResourcesParam, string> = {
  Articles: 'Artigos',
  ArticleItems: 'Descrição Artigos',
  BreastfeedAddBreastfeeding: 'Adicionar mamada',
  BreastfeedBabyWasBorn: 'Criança nasceu',
  BreastfeedEndBreastfeeding: 'Finalizar amamentação',
  BreastfeedGetAgeMonths: 'Obter idade da criança',
  BreastfeedGetAmountSupplementation: 'Quantidade de suplemento',
  BreastfeedGetHowToFeed: 'Como se alimenta',
  BreastfeedGetNameGenre: 'Cadastrar nova criança',
  BreastfeedHistory: 'Monitor amamentação',
  BreastfeedHistoryEdit: 'Monitor amamentação edição',
  BreastfeedSaveDiaryBreastfeeding: 'Salvar Diário de amamentação',
  BreastfeedStartBreastfeeding: 'Iniciar amamentação',
  Chat: 'Chat',
  ChooseCategory: 'Escolha a fase',
  ChooseWeek: 'Escolha a semana',
  ChooseWeekInitialDate: 'Escolha a data da semana',
  Diary: 'Diário',
  DiaryScreen: 'Diário',
  FertileDigitalTable: 'Tabela fértil',
  FertileDigitalTableChooseDate: 'Resultado tabela fértil',
  FertileDigitalTableHistoric: 'Histórico tabela fértil',
  FrequentAsk: 'Perguntas frequents',
  ForgotMyPassword: 'Esqueci minha senha',
  Home: 'Home',
  Introduction: 'Inicio',
  Perfil: 'Perfil',
  PerfilMenu: 'Perfil',
  PrivacyPolicy: 'Termos e Politica de Privacidade',
  Policy: 'Politica de Privacidade',
  Quiz: 'Quiz',
  QuizAnswer: 'Quiz responder',
  QuizResult: 'Quiz resultado',
  SignIn: 'Login',
  SignUp: 'Cadastro',
  Sms: 'Sms',
  TabHome: 'Home',
  Terms: 'Confirma termos',
  TermCondition: 'Termos e Condições',
  Test: 'Teste',
  Testes: 'Testes',
  UpdateUser: 'Atualizar dados usuário',
  Week: 'Semana a semana',
  WeekDescription: 'Semana descrição',
  Videos: 'Videos',
}
